/**
 * Phase 52 — Canonical `location` vocab. [TAG-07]
 *
 * 130+ spelled-out values: US/CA/EU/APAC/LATAM/MEA + remote variants.
 * Hard filter intersect with `anywhere` bypass (MATCH-04).
 *
 * Adam-locked:
 *  - D5: spelled-out, no abbreviations (`san_francisco_bay_area` not `sf`)
 *
 * Convention: city-level uses metro/region (e.g., `san_francisco_bay_area`,
 * `new_york_metro`) so we don't fragment between South Bay / SF / Berkeley etc.
 * Country-level disambiguator suffixes added where needed
 * (`london_united_kingdom`, `dublin_ireland`).
 */

import { z } from "zod"

export const LOCATION_VOCAB = [
  // ─── United States — major metros ───
  "san_francisco_bay_area",
  "new_york_metro",
  "los_angeles_metro",
  "seattle_metro",
  "boston_metro",
  "chicago_metro",
  "austin_metro",
  "denver_metro",
  "portland_oregon",
  "washington_dc_metro",
  "atlanta_metro",
  "miami_metro",
  "philadelphia_metro",
  "dallas_fort_worth",
  "houston_metro",
  "raleigh_durham",
  "minneapolis_st_paul",
  "san_diego",
  "salt_lake_city",
  "phoenix",
  "detroit",
  "st_louis",
  "kansas_city",
  "indianapolis",
  "columbus_ohio",
  "cleveland",
  "pittsburgh",
  "nashville",
  "charlotte",
  "tampa",
  "orlando",
  "jacksonville",
  "las_vegas",
  "sacramento",
  "providence",
  "hartford",
  "richmond_virginia",
  "milwaukee",
  "cincinnati",
  "buffalo",
  "rochester_new_york",
  "albuquerque",
  "boise",
  "honolulu",
  "anchorage",
  "tucson",
  "ann_arbor",
  "madison_wisconsin",
  "santa_barbara",
  "reno",
  // ─── Canada ───
  "toronto",
  "vancouver",
  "montreal",
  "ottawa",
  "calgary",
  "edmonton",
  "waterloo_ontario",
  "quebec_city",
  "halifax",
  "winnipeg",
  // ─── European Union + UK ───
  "london_united_kingdom",
  "manchester_united_kingdom",
  "edinburgh_united_kingdom",
  "cambridge_united_kingdom",
  "oxford_united_kingdom",
  "dublin_ireland",
  "berlin",
  "munich",
  "hamburg",
  "frankfurt",
  "amsterdam",
  "rotterdam",
  "paris",
  "lyon",
  "stockholm",
  "gothenburg",
  "copenhagen",
  "zurich",
  "geneva",
  "vienna",
  "prague",
  "warsaw",
  "krakow",
  "barcelona",
  "madrid",
  "valencia",
  "lisbon",
  "porto",
  "helsinki",
  "oslo",
  "brussels",
  "luxembourg_city",
  "budapest",
  "athens",
  "milan",
  "rome",
  "tallinn",
  "riga",
  "vilnius",
  "reykjavik",
  // ─── Asia Pacific ───
  "singapore",
  "tokyo",
  "osaka",
  "kyoto",
  "yokohama",
  "hong_kong",
  "shanghai",
  "beijing",
  "shenzhen",
  "guangzhou",
  "hangzhou",
  "chengdu",
  "seoul",
  "busan",
  "sydney",
  "melbourne",
  "brisbane",
  "perth",
  "auckland",
  "wellington",
  "bangalore",
  "mumbai",
  "delhi_ncr",
  "hyderabad",
  "chennai",
  "pune",
  "kolkata",
  "taipei",
  "kaohsiung",
  "bangkok",
  "ho_chi_minh_city",
  "hanoi",
  "kuala_lumpur",
  "jakarta",
  "manila",
  // ─── Latin America ───
  "sao_paulo",
  "rio_de_janeiro",
  "mexico_city",
  "guadalajara",
  "monterrey",
  "buenos_aires",
  "bogota",
  "medellin",
  "santiago",
  "lima",
  "san_jose_costa_rica",
  "panama_city",
  "quito",
  "montevideo",
  // ─── Middle East + Africa ───
  "tel_aviv",
  "haifa",
  "dubai",
  "abu_dhabi",
  "riyadh",
  "doha",
  "istanbul",
  "ankara",
  "cairo",
  "johannesburg",
  "cape_town",
  "nairobi",
  "lagos",
  "accra",
  "casablanca",
  "addis_ababa",
  // ─── Remote variants ───
  "remote_united_states",
  "remote_canada",
  "remote_europe",
  "remote_united_kingdom",
  "remote_apac",
  "remote_latam",
  "remote_global",
  "remote_anywhere",
  "remote_americas",
  "remote_emea",
] as const

export type Location = (typeof LOCATION_VOCAB)[number]

export const LocationSchema = z.enum(LOCATION_VOCAB)

export const LocationListSchema = z.array(LocationSchema)

/** Bypass token for "open to anywhere" preference. */
export const ANYWHERE_LOCATION_TOKENS: ReadonlySet<Location> = new Set([
  "remote_anywhere",
  "remote_global",
])
